<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEtudiants()
    {
        $query=$this->getEntityManager()->createQuery("SELECT u FROM AppBundle:User u
WHERE p.roles like '%ROLE_ETUDIANT%'");
        return $query->getResult();
    }


}
