<?php

namespace ClassesBundle\Repository;

/**
 * BrancheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrancheRepository extends \Doctrine\ORM\EntityRepository
{
}
