<?php

namespace ClassesBundle\Repository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchEtudiants($input)
    {
        $query=$this->getEntityManager()->createQuery("SELECT c FROM AppBundle:User c WHERE c.classe='$input'");
        return $query->getResult();
    }

    public function searchC($input)
    {
        $x= "%".$input."%";
        $query=$this->getEntityManager()->createQuery("SELECT c FROM ClassesBundle:Classe c WHERE c.nom like '$x'");
        return $query->getResult();
    }
}
