<?php

namespace LibBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findalltri(){
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.nom', 'ASC');
        $query = $qb->getQuery();

        return $query->execute();
    }


}
