<?php

namespace LibBundle\Repository;

use LibBundle\Entity\Categorie;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBycat(Categorie $cat){
        $qb = $this->createQueryBuilder('p')
            ->where('p.categorie = :c')
            ->setParameter('c',$cat);
        $query = $qb->getQuery();

        return $query->execute();
    }

    public function findallBycat(int $cat){
        $qb = $this->createQueryBuilder('p')
            ->where('p.categorie = :c')
            ->setParameter('c',$cat);
        $query = $qb->getQuery();

        return $query->execute();
    }

    public function finddis(){
        $qb = $this->createQueryBuilder('p')
            ->where('p.disponible = :c')
            ->setParameter('c','true');
        $query = $qb->getQuery();

        return $query->execute();
    }

}
