<?php

namespace LibBundle\Repository;

/**
 * ommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ommentRepository extends \Doctrine\ORM\EntityRepository
{
}
