<?php

namespace LibBundle\Repository;

/**
 * rateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rateRepository extends \Doctrine\ORM\EntityRepository
{
}
