<?php

namespace ModuleBundle\Repository;

use ModuleBundle\Entity\matiere;

/**
 * chapitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chapitreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBymat(matiere $mat){
        $qb = $this->createQueryBuilder('p')
            ->where('p.matiere = :c')
            ->setParameter('c',$mat);
        $query = $qb->getQuery();

        return $query->execute();
    }
}
