<?php

namespace ModuleBundle\Repository;

use ModuleBundle\Entity\module;

/**
 * matiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matiereRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBymod(module $mod){
        $qb = $this->createQueryBuilder('p')
            ->where('p.module = :c')
            ->setParameter('c',$mod);
        $query = $qb->getQuery();

        return $query->execute();
    }
}
