<?php

namespace LogistiqueBundle\Repository;

/**
 * chambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chambreRepository extends \Doctrine\ORM\EntityRepository
{
}