<?php

namespace LogistiqueBundle\Repository;

/**
 * ligneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneRepository extends \Doctrine\ORM\EntityRepository
{
}
